export const usage = [
  'Wake - an autonomous agent control plane for software development.',
  '',
  'Usage:',
  '  wake init <path>           Scaffold a new Wake home directory',
  '  wake sandbox <subcommand>  Build/run/manage the Docker sandbox (build, up, update, down, stop, self-update, setup, exec, logs, resume)',
  '  wake tick                  Run one control-plane tick',
  '  wake start                 Run the resident loop',
  '  wake validate-state        Validate .wake/ control-plane state health',
  '  wake stop                  Wait for active runs to finish',
  '  wake smoke                 Smoke-test the configured runner',
  '  wake ui                    Run the control-plane UI server',
  '  wake audit                 Show autonomous decision audit history',
  '  wake correlate             Manually correlate a resource to a work item',
  '  wake run resolve           Resolve an escalated ambiguous run',
  '  wake doctor                Diagnose config/GitHub/Docker/sandbox setup problems',
  '  wake --version             Print the installed Wake version',
  '  wake --help                Show this message',
  '',
  'Additional target commands:',
  '  wake run resolve <run-id> --succeeded (--outcome <json> | --outcome-file <path>)',
  '  wake run resolve <run-id> --failed --reason <message>',
  '  wake api                   Run the target API surface',
  '  wake sandbox-entrypoint    Run the sandbox resident entrypoint',
  '  wake self-update           Safely update a source installation',
  '',
  'Getting started:',
  '  1. wake init ./wake-home',
  '  2. cd wake-home && wake start',
  '  https://github.com/atolis-hq/wake#readme',
  '',
  'Runtime commands (tick/start/ui/smoke/audit/correlate/validate-state) auto-delegate into the sandbox',
  'when docker/Dockerfile exists at --wake-root (i.e. after `wake sandbox build`),',
  'defaulting --wake-root to the current directory. Pass --no-sandbox to run',
  'directly on the host instead.',
].join('\n');
